backend/controllers/ClientController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\User;
use common\models\Profile;
use common\models\UserProfileSearch;

class ClientController extends \yii\web\Controller {

    public function actionIndex() {
        $searchModel = new UserProfileSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->get());
        return $this->render('index', ['dataProvider' => $dataProvider, 'searchModel' => $searchModel]);
    }
    
    public function actionDelete($id = false) {
        User::deleteAll(["id" => $id]);
        return $this->redirect(['index']);
    }
    
    public function actionLock($id = false) {
        User::setStatusDeny($id);
        return $this->redirect(['index']);
    }
    
    public function actionActive($id = false) {
        User::setStatusActive($id);
        return $this->redirect(['index']);
    }
    
    public function actionHide($id = false) {
        User::setStatusHidden($id);
        return $this->redirect(['index']);
    }
    
    public function actionAdd() {
        $userModel = new \frontend\models\SignupForm;
        $userModel->setDefaultValue();
        $profileModel = new Profile;
        $profileModel->user_id = 0;
        if ($userModel->load(Yii::$app->request->post()) && $profileModel->load(Yii::$app->request->post()) ) {
            if ($userModel->validate()) {
                if ($user = $userModel->signup()) {
                    $profileModel->user_id = $user->id;
                    if ($profileModel->_temp_date) $profileModel->birthday = strtotime($profileModel->_temp_date);
                    if ($profileModel->validate()) {
                        $profileModel->save();
                        return $this->redirect('index');
                    }
                    else print_r($profileModel); echo "1"; die();
                }
            }
        }
        return $this->render('_form', ['user' => $userModel, 'profile' => $profileModel]);
    }

    public function actionUpdate($id) {
        $userModel = User::findOne(["id" => $id]);
        if (!$userModel) return $this->redirect ("add");
        $profileModel = Profile::findOne(["user_id" => $id]);
        if (!$profileModel) {
            $profileModel = new Profile;
            $profileModel->user_id = $id;
        }
        if ($profileModel->birthday) 
            $profileModel->_temp_date = Yii::$app->formatter->asDate($profileModel->birthday, 'dd.MM.yyyy');
        if ($userModel->load(Yii::$app->request->post()) && $profileModel->load(Yii::$app->request->post()) ) {
            if ($userModel->validate()) {
                if ($userModel->update()) {
                    $profileModel->birthday = strtotime($profileModel->_temp_date);
                    if ($profileModel->validate()) {
                        $profileModel->save();
                        return $this->redirect('index');
                    }
                }
            }
        }
        return $this->render('_form', ['user' => $userModel, 'profile' => $profileModel, "update" => 1]);
    }

}

backend/views/client/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;
use common\models\User;
use dosamigos\fileupload\FileUploadUI;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form ActiveForm */

$this->params['breadcrumbs'] = [ 
    ["label" => "Clients", "url" => "/client/index"],
    isset($update)?$user->username:"New user"
];
?>
<h1><?= empty($update)?"Create new ":"Update " ?>user</h1>
<div class="client-update">
    
    <?php  
    $form = ActiveForm::begin(/*[
                //'enableClientValidation' => false,
                'options' => [
                    'enctype' => 'multipart/form-data',
                ],
    ]*/);
    ?>
    
        
    
        <?= $form->field($profile, 'user_id')->hiddenInput()->label('') ?>
        <?php 
        if (!isset($update)) {
            echo $form->field($user, 'username');
            echo $form->field($user, 'password');
        }   
        ?>
        <?= $form->field($user, 'email') ?>
             
        <?= $form->field($profile, 'firstname') ?>
        <?= $form->field($profile, 'lastname') ?>
        <?php $form->field($user, 'note')->textarea() ?>
        <?php 
        echo $form->field($profile, '_temp_date')->widget(DatePicker::className(), [
            'dateFormat' => 'yyyy-MM-dd',
            'options' => [
                'autoclose' => true,
            ]
        ]);
        ?>
        <?php 
        $_user = new User;
        echo $form->field($user, 'status')->dropDownList($_user->getStatusList());
        ?>
    
        <div class="form-group">
            <?= Html::submitButton(isset($update)?Yii::t('client', 'Update'):Yii::t('client', 'Submit'), ['class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- client-update -->

backend/views/client/index.php
<?php
/* @var $this yii\web\View */
use \Yii;
use yii\grid\GridView;
use yii\helpers\Html;
use \yii\widgets\Pjax;
use common\models\User;

$this->params['breadcrumbs'] = [ 
    "Clients", 
];
?>
<h1><?= Yii::t("client", "Clients overview") ?></h1>
<p>
<script type="text/javascript">
    $(function(){
        $('body').on('click', '.grid-action', function(e){
            var href = $(this).attr('href');
            var self = this;
            $.get(href, function(){
                var pjax_id = $(self).closest('.pjax-wraper').attr('id');
                $.pjax.reload('#' + pjax_id);
            });
            return false;
        })
    });
</script>
<?php
$gridColumns = [
    'id' => [
        'attribute' => 'id',
        'filter' => false,
    ], 
    'username',
    'email',
    [
        'format' => 'raw',
        'header' => 'FIO',
        'value' => function($model) {
            return $model->profile['firstname']." ".$model->profile['lastname'];
        },
        'filter' => false,
    ],
    
//    [
//        'attribute' => 'firstname',
//        'value' => 'profile.firstname'
//    ],
//    [
//        'attribute' => 'lastname',
//        'value' => 'profile.lastname'
//    ],
    [
        'attribute' => 'note',
        'filter' => false,
    ],
    
    [
        'attribute' => 'birthday',
        'format' => 'raw',
        'filter' => false,
        'value' => function ($model) {                      
            return ($model->profile['birthday'])?date("Y-m-d", $model->profile['birthday']):"";
        },
    ],
    [
        'attribute' => 'status',
        'format' => 'raw',
        'filter' => false,
        'value' => function($model) {
            return $model->getStatusAttribute();
        },
    ],
    [  
        'class' => 'yii\grid\ActionColumn',
        'contentOptions' => ['style' => 'width:110px;'],
        'header'=>'Actions',
        'buttons'=>[
            'update' => function ($url, $model) {
                if (!Yii::$app->user->can("/client/update")) return;
                return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                    'title' => Yii::t('yii', 'Update'),
                    'data-pjax'=>'w0',
                ]);
            },
            'active' => function ($url, $model) {
                if (!Yii::$app->user->can("/client/active")) return;
                return Html::a('<span class="glyphicon glyphicon-check"></span>', $url, [
                    'title' => Yii::t('yii', 'Active'),
                    'data-pjax'=>'w0',
                ]);
            },
            'lock' => function ($url, $model) {
                if (!Yii::$app->user->can("/client/lock")) return;
                return Html::a('<span class="glyphicon glyphicon-lock"></span>', $url, [
                    'title' => Yii::t('yii', 'Deny'),
                    'data-pjax'=>'w0',
                ]);
            },
            'hide' => function ($url, $model) {
                if (!Yii::$app->user->can("/client/hide")) return;
                return Html::a('<span class="glyphicon glyphicon-eye-close"></span>', $url, [
                    'title' => Yii::t('yii', 'Hide'),
                    'data-pjax'=>'w0',
                ]);
            },
            'delete' => function ($url, $model) {
                if (!Yii::$app->user->can("/client/delete")) return;
                return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                    'title' => Yii::t('yii', 'Delete'),
                    'data-pjax' => '0', 
                    'class' => 'grid-action'
                ]);
            }
        ],
        'visible' => (Yii::$app->user->can("client") || Yii::$app->user->can("client_status")),
        'template' => '{update} {active} {lock} {hide} {delete}',

       ],
        
];
Pjax::begin(['options' => ['class' => 'pjax-wraper']]);
echo GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => $gridColumns,
]);
Pjax::end();
?>
</p>
<p>
    <?php if (Yii::$app->user->can("/client/add")) { ?>
    <?= Html::a(Yii::t('client', 'Add new client'), ['add'], ['class' => 'btn btn-success']) ?>
    <?php } ?>
</p>