common/models/Inquery.php
<?php

namespace common\models;

use Yii;
use \yii\data\ActiveDataProvider;
use common\models\Message;
use common\models\ActiveRecord;

/**
 * This is the model class for table "inquery".
 *
 * @property integer $id
 * @property integer $product_id
 * @property integer $user_id
 * @property string $message
 * @property string $number
 * @property integer $quantity
 * @property string $price
 * @property integer $timestamp
 * @property integer $status
 *
 * @property Product $product
 * @property User $user
 */
class Inquery extends ActiveRecord {

    const STATUS_NEW = 1;
    const STATUS_IN_VIEW = 2;
    const STATUS_IN_PROCESS = 3;
    const STATUS_CLOSED = 4;
    const STATUS_DELETED = 5;
    
    public $_skip;
    public $username;
    public $product;
    public $_temp_date;

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'inquery';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['product_id', 'user_id', 'quantity', 'timestamp'], 'integer'],
            ['status', 'default', 'value' => self::STATUS_NEW],
            ['status', 'in', 'range' => [self::STATUS_NEW, self::STATUS_IN_VIEW, self::STATUS_IN_PROCESS, self::STATUS_CLOSED, self::STATUS_DELETED]],
            [['price'], 'number'],
            [['message'], 'string', 'max' => 512],
            [['number'], 'string', 'max' => 255],
            [['product', 'username', '_temp_date'], 'safe'],
            [['_temp_date'], 'date', 'format' => 'yyyy-MM-dd'],
            
            ['product', 'check_product', 'message' => "Product not found", "skipOnEmpty" => false],
            ['username', 'check_user', 'message' => "Client not found", "skipOnEmpty" => false],
        ];
    }
    
    public function check_product($attribute, $params) {
        if (!$this->$attribute && $this->isNewRecord && !$this->_skip) {
            $this->addError($attribute, $params['message']);
        }
    }
    
    public function check_user($attribute, $params) {
        if (!$this->$attribute && $this->isNewRecord  && !$this->_skip) {
            $this->addError($attribute, $params['message']);
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => Yii::t('inquery', 'ID'),
            'product_id' => Yii::t('inquery', 'Product ID'),
            'user_id' => Yii::t('inquery', 'User ID'),
            'message' => Yii::t('inquery', 'Message'),
            'number' => Yii::t('inquery', 'Number'),
            'quantity' => Yii::t('inquery', 'Quantity'),
            'price' => Yii::t('inquery', 'Price'),
            'timestamp' => Yii::t('inquery', 'Timestamp'),
            'status' => Yii::t('inquery', 'Status'),
            'username' => Yii::t('inquery', 'Select client'),
            'product' => Yii::t('inquery', 'Select product'),
            '_temp_date' => Yii::t('inquery', 'Query date'),
        ];
    }

    public static function generateBaseModel($number = false) {
        $product = Product::findProduct($number);
        $model = new Inquery;
        if (!Yii::$app->user->isGuest)
            $model->user_id = Yii::$app->user->id;
        $model->_skip = false;
        $model->timestamp = time();
        if ($product) {
            $model->product_id = $product->id;
            $model->number = $number;
            //$model->quantity = $product->quantity;
            //$model->price = $product->price;
        }
        return $model;
    }

    public function search($params, $id = false, $_active = false) {
        $query = ($id) ? Inquery::find(["user_id" => $id]) : Inquery::find();
        if ($_active)
            $query->where("status > :status", [":status" => self::STATUS_NEW]);
        $query->orderBy("timestamp DESC");
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        if (!($this->load($params) && $this->validate())) {
            return $dataProvider;
        }

        $query->andFilterWhere(['like', 'number', $this->number]);

        return $dataProvider;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct() {
        return $this->hasOne(Product::className(), ['id' => 'product_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser() {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function afterSave($insert, $changedAttributes) {
        parent::afterSave($insert, $changedAttributes);
        if ($this->isNewRecord) {
            $message = Message::generateBaseModel([
                "model" => $this, 
                "model_id" => $this->id, //Нужно обязательно
                "from" => $this->user_id, 
                "text" => $this->message
            ]);
            if ($message->validate())
                $message->save();
            else {print_r($message->getErrors()); die();}
        }
    }
    
    public static function inWish($product_id = false, $user_id = false) {
        if (!$user_id && !Yii::$app->user->isGuest) 
            $user_id = Yii::$app->user->id;
        return Inquery::find()->where(["product_id" => $product_id, "user_id" => $user_id])->count()?true:false;
    }
    
    public function getStatusAttribute($status_state = false) {
        $status = "none";
        $s = ($status_state)?$status_state:$this->status;
        switch($s) {
            case Inquery::STATUS_NEW: 
                $status = Yii::t("client", "New");
                break;
            case Inquery::STATUS_IN_VIEW: 
                $status = Yii::t("client", "View");
                break;
            case Inquery::STATUS_IN_PROCESS: 
                $status = Yii::t("client", "Process");
                break;
            case Inquery::STATUS_CLOSED: 
                $status = Yii::t("client", "Close");
                break;
            case Inquery::STATUS_DELETED: 
                $status = Yii::t("client", "Delete");
                break;
        }
        return $status;
    }
    
    public function prepareForReply($id) {
        $model = Inquery::findOne(["id" => $id]);
        $clone = new Inquery;
        $clone->attributes = $model->attributes;
        $clone->product = Product::getTitle($model->number);
        $clone->username = User::getUsername($model->user_id);
        $clone->timestamp = time();
        $clone->_temp_date = date("Y-m-d", $clone->timestamp);
        $clone->message = "Re: ".$model->message;
        $clone->status = self::STATUS_NEW;
        return $clone;
    }

}

backend/controllers/InqueryController.php
<?php

namespace backend\controllers;

use Yii;
use \yii\web\Controller;
use common\models\Inquery;
use \common\models\Product;
use common\models\User;
use common\models\Message;

class InqueryController extends \yii\web\Controller {

    public function actionIndex() {
        $searchModel = new Inquery();
        $dataProvider = $searchModel->search(Yii::$app->request->get());
        return $this->render('index', ['dataProvider' => $dataProvider, 'searchModel' => $searchModel]);
    }
    
    public function actionAdd() {
        $model = new Inquery;
        $model->message = "System inquery";
        if ($model->load(Yii::$app->request->post())) {
            if ($product = Product::findOne(["id" => $model->product_id]))
                $model->number = $product->number;
            if ($model->validate()) {
                $model->save ();
                return $this->redirect("index");
            }
        }

        return $this->render('_add', ['model' => $model, ]);
    }

    public function actionUpdate($id = false) {
        $model = Inquery::findOne(["id" => $id]);

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                $model->update ();
                return $this->redirect("index");
            }
        }
        
        $message = Message::generateBaseModel(['model' => $model]);
        //Если есть сообщение, то обрабатываем его и завершаем запрос
        if (Message::Send()) 
            Yii::$app->end();
        
        $searchModel = new Message();
        $dataProvider = $searchModel->searchByInquery(Yii::$app->request->get(), $model->id);

        return $this->render('_update', ['model' => $model, "searchModel" => $searchModel, "dataProvider" => $dataProvider, "message" => $message]);
    }
    
    public function actionReply($id = false) {
        $model = Inquery::prepareForReply($id);
        if ($model->load(Yii::$app->request->post())) {
            if ($product = Product::findOne(["id" => $model->product_id]))
                $model->number = $product->number;
            if ($model->validate()) {
                $model->save();
                return $this->redirect("index");
            }
        }

        return $this->render('_add', ['model' => $model, "reply" => true]);
    }
    
    public function actionView($id) {
        Inquery::updateAll(["status" => Inquery::STATUS_IN_VIEW], ["id" => $id]);
    }
    
    public function actionProcess($id) {
        Inquery::updateAll(["status" => Inquery::STATUS_IN_PROCESS], ["id" => $id]);
    }
    
    public function actionDelete($id) {
        //Inquery::updateAll(["status" => Inquery::STATUS_DELETED], ["id" => $id]);
        Inquery::deleteAll(["id" => $id]);
    }
    
    public function actionClose($id) {
        Inquery::updateAll(["status" => Inquery::STATUS_CLOSED], ["id" => $id]);
    }

}

frontend/controllers/InqueryController.php
<?php

namespace frontend\controllers;

use Yii;
use \yii\web\Controller;
use common\models\Inquery;
use common\models\Product;
use common\models\Message;

class InqueryController extends Controller {
    
    public function actionIndex() {
        if (Yii::$app->user->isGuest)
            return $this->redirect ("/site/index");
        $searchModel = new Inquery();
        $dataProvider = $searchModel->search(Yii::$app->request->get(), Yii::$app->user->id, false);
        return $this->render('index', ['dataProvider' => $dataProvider, 'searchModel' => $searchModel]);
    }

    public function actionForm($number, $skip = false) {
        if (Yii::$app->user->isGuest)
            return $this->redirect ("/site/index");
        $model = Inquery::generateBaseModel($number);
        $model->_skip = $skip;
        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                $model->save (); //Так же добавляет новую запись в таблицу Message
                return $this->render('_form', ["model" => $model, "number" => $number]);
                Yii::$app->end();
            }
        }
        return $model;
    }
    
    public function actionView($id = false) {
        $model = Inquery::findOne(["id" => $id]);
        
        $message = Message::generateBaseModel(['model' => $model]);
        //Если есть сообщение, то обрабатываем его и завершаем запрос
        if (Message::Send()) 
            Yii::$app->end();
        
        $searchModel = new Message();
        $dataProvider = $searchModel->searchByInquery(Yii::$app->request->get(), $model->id);

        return $this->render('view', ['model' => $model, "searchModel" => $searchModel, "dataProvider" => $dataProvider, "message" => $message]);
    }
    
    public function actionReply($id = false) {
        $model = Inquery::prepareForReply($id);
        if ($model->load(Yii::$app->request->post())) {
            if ($product = Product::findOne(["id" => $model->product_id]))
                $model->number = $product->number;
            if ($model->validate()) {
                $model->save();
                return $this->redirect("index");
            }
        }

        return $this->render('reply', ['model' => $model, "id" => $id, "reply" => true]);
    }
    
    public function actionClose($id) {
        Inquery::updateAll(["status" => Inquery::STATUS_CLOSED], ["id" => $id]);
    }

}

backend/views/inquery/_add.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;
use common\models\Product;
use common\models\User;
use common\models\Inquery;
use yii\helpers\ArrayHelper;
use yii\jui\AutoComplete;
use yii\web\JsExpression;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model common\models\Inquery */
/* @var $form ActiveForm */
$this->params['breadcrumbs'] = [ 
    ["label" => "Inqueries", "url" => "/inquery/index"],
    isset($reply)?"Reply inquery":"New inquery", 
];
?>
<h1><?= isset($reply)?"Reply":"New" ?> inquery</h1>

<div class="form">
    <?php $form = ActiveForm::begin(); ?>
        <?= $form->field($model, '_skip')->hiddenInput()->label(false) ?>
        <?php
        echo $form->field($model, 'product_id')->hiddenInput()->label(false);
        $product = Product::find()->select(['title as label', 'id'])->asArray()->all();
        echo $form->field($model, 'product')->widget(AutoComplete::classname(), [
            'name' => 'product',
            'clientOptions' => [
                'source' => $product,
                'autoFill'=>true,
                'minLength'=> 0,
                'select' => new JsExpression("function( event, ui ) {
                    $('#inquery-product_id').val(ui.item.id);
                }")
            ],
            'options' => ['class' => 'combobox'] //Автооткрытие по клику
        ]);
        ?>
        <?php
        echo $form->field($model, 'user_id')->hiddenInput()->label(false);
        $user = User::find()->select(['username as label', 'id'])->asArray()->all();
        echo $form->field($model, 'username')->widget(AutoComplete::classname(), [
            'name' => 'username',
            'clientOptions' => [
                'source' => $user,
                'autoFill'=>true,
                'minLength'=> 0,
                'select' => new JsExpression("function( event, ui ) {
                    $('#inquery-user_id').val(ui.item.id);
                }")
            ],
            'options' => ['class' => 'combobox'] //Автооткрытие по клику
        ]);
        ?>
        <?php 
        echo $form->field($model, '_temp_date')->widget(DatePicker::className(), [
            'dateFormat' => 'yyyy-MM-dd',
            'options' => [
                'autoclose' => true,
            ]
        ]);
        ?>
        <?= $form->field($model, 'price') ?>
        <?= $form->field($model, 'quantity') ?>
        <?= $form->field($model, 'message')->textarea() ?>
        <?php 
        $_inquery = new Inquery;
        echo $form->field($model, 'status')->dropDownList($_inquery->getRangeList('status'));
        ?>
        <div class="form-group">
            <?= Html::submitButton(Yii::t('inquery', isset($reply)?"Reply":"Update"), ['class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- _form -->

backend/views/inquery/_update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;
use common\models\Product;
use common\models\User;
use common\models\Inquery;
use common\models\Message;

/* @var $this yii\web\View */
/* @var $model common\models\Inquery */
/* @var $form ActiveForm */
$this->params['breadcrumbs'] = [ 
    ["label" => "Inqueries", "url" => "/inquery/index"],
    "View inquery", 
];
?>
<h1>View inquery</h1>
<?php 
$product = ($model->product_id)?Product::isValid($model->product_id):false;
echo DetailView::widget([
    'model' => $model,
    'attributes' => [
        
        [
            'label' => 'Product',
            'format'=>'raw',
            'value' => !empty($product)?Html::a($product->title." (".$model->number.")", "/product/update?id=".$model->product_id):$model->number,
        ],
        [
            'label' => 'From client',
            'format' => 'raw',
            'value' => !empty($model->user_id)?Html::a(User::getUsername($model->user_id), ["client/update", "id" => $model->user_id]):"none",
        ],
        [
            'label' => 'Date',
            'value' => $model->timestamp?date("Y-m-d G:i:s", $model->timestamp):"none",
        ],
        'message'
    ]
]);
?>

<div class="form">
    <?php $form = ActiveForm::begin(); ?>
        <?= $form->field($model, 'price') ?>
        <?= $form->field($model, 'quantity') ?>
        <?php 
        $_inquery = new Inquery;
        echo $form->field($model, 'status')->dropDownList($_inquery->getRangeList('status'));
        ?>
        <div class="form-group">
            <?= Html::submitButton(Yii::t('inquery', 'Update'), ['class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- _form -->

<h1>Messages</h1>
<?= $this->render("/message/_list", ['dataProvider' => $dataProvider, "model" => Message::generateBaseModel(), "message" => $message]) ?>

backend/views/inquery/index.php
<?php
/* @var $this yii\web\View */
use yii\grid\GridView;
use yii\helpers\Html;
use \yii\widgets\Pjax;
use common\models\User;

$this->params['breadcrumbs'] = [ 
    "Inqueries", 
];
?>
<h1>Inqueries overview</h1>

<p>
    <?php
    $gridColumns = [
        'id' => [
            'attribute' => 'id',
            'filter' => false,
        ],
        'user_id' => [
            'attribute' => 'user_id',
            'filter' => false,
            'format' => 'raw',
            'value' => function($model) {
                return Html::a(User::getUsername($model->user_id), ["client/update", "id" => $model->user_id]);
            }
        ],
        [
            'attribute' => 'number',
            'format' => 'raw',
            'value' => function($model) {
                return !empty($model->product_id)?Html::a($model->number, ["product/update", "id" => $model->product_id]):$model->number;
            }
        ],
        [
            'attribute' => 'message',
            'filter' => false,
        ],
        'quantity' => [
            'attribute' => 'quantity',
            'filter' => false,
        ],
        'price' => [
            'attribute' => 'price',
            'filter' => false,
        ],
        'timestamp' => [
            'attribute' => 'timestamp',
            'format' => 'raw',
            'filter' => false,
            'value' => function ($model) {                      
                return ($model->timestamp)?date("Y-m-d G:i:s", $model->timestamp):"";
            },
        ],
        [
            'attribute' => 'status',
            'format' => 'raw',
            'filter' => false,
            'value' => function($model) {
                return $model->getStatusAttribute();
            },
        ],
        [  
        'class' => 'yii\grid\ActionColumn',
        'contentOptions' => ['style' => 'width:110px;'],
        'header'=>'Actions',
        'buttons'=>[
            'update' => function ($url, $model) {
                return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                    'title' => Yii::t('yii', 'Update'),
                    'data-pjax'=>'0',
                ]);
            },
            'view' => function ($url, $model) {
                return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                    'title' => Yii::t('yii', 'View'),
                    'data-pjax'=>'0',
                    'class' => 'grid-action'
                ]);
            },
            'process' => function ($url, $model) {
                return Html::a('<span class="glyphicon glyphicon-share-alt"></span>', $url, [
                    'title' => Yii::t('yii', 'Process'),
                    'data-pjax'=>'0',
                    'class' => 'grid-action'
                ]);
            },
            'reply' => function ($url, $model) {
                return Html::a('<span class="glyphicon glyphicon-repeat"></span>', $url, [
                    'title' => Yii::t('yii', 'Reply'),
                    'data-pjax'=>'0',
                    //'class' => 'grid-action'
                ]);
            },
            'close' => function ($url, $model) {
                return Html::a('<span class="glyphicon glyphicon-ok"></span>', $url, [
                    'title' => Yii::t('yii', 'Close'),
                    'data-pjax' => '0', 
                    'class' => 'grid-action'
                ]);
            },
            'delete' => function ($url, $model) {
                return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                    'title' => Yii::t('yii', 'Delete'),
                    'data-pjax' => '0', 
                    'class' => 'grid-action'
                ]);
            }
        ],
        'template' => '{update} {reply} {close}',

       ],

    ];
    Pjax::begin(['options' => ['class' => 'pjax-wraper']]);
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $gridColumns,
    ]);
    Pjax::end();
    ?>
</p>
<p>
    <?php if (Yii::$app->user->can("/inquery/add")) { ?>
    <?= Html::a(Yii::t('client', 'Add new inquery'), ['add'], ['class' => 'btn btn-success']) ?>
    <?php } ?>
</p>